import "@/styles/globals.css";
import type { AppProps } from "next/app";
import wrapper from "../store";
import "../styles/main.css";
import Head from "next/head";
import { Provider } from "react-redux";
import { MoralisProvider } from "react-moralis";
import { ThirdwebProvider } from "@thirdweb-dev/react";

export default function App({ Component, ...rest }: AppProps) {
  const { store, props } = wrapper.useWrappedStore(rest);
  const { pageProps } = props;
  return (
   <ThirdwebProvider>
    <MoralisProvider appId={""} serverUrl={""}>
      <Provider store={store}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </Provider>
    </MoralisProvider>
      </ThirdwebProvider>
  );
}
