import "@/styles/globals.css";
import type { AppProps } from "next/app";
import wrapper from "../store";
import Head from "next/head";
import { Provider } from "react-redux";
import { ThirdwebProvider } from "@thirdweb-dev/react";

export default function App({ Component, ...rest }: AppProps) {
  const { store, props } = wrapper.useWrappedStore(rest);
  const { pageProps } = props;
  return (
    <ThirdwebProvider activeChain="ethereum">
        <Provider store={store}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </Provider>
    </ThirdwebProvider>
  );
}
